/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.retrylife.robohook;

public class App {

    public static void main(String[] args) {
        (new App()).run();
    }

    App(){

    }

    public void run() {
        
    }
}
